global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/alerts.yaml

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

scrape_configs:
  - job_name: inferencia
    metrics_path: /metrics
    scrape_interval: 10s
    static_configs:
      - targets: ["inferencia:8080"]
        labels:
          service: inferencia
          environment: production
